[build]
builder = "RAILPACK"
buildCommand = "npm i -g pnpm && cd widgets && pnpm install && BASE_URL=https://openai-apps-sdk-examples-production-5ed8.up.railway.app pnpm run build && cd ../razorpay_server_node && pnpm install"

[deploy]
startCommand = "cd razorpay_server_node && pnpm run start"
