name: Lint
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - uses: razorpay/create-github-app-token@v1
        name: Generate Github Token
        id: app-token
        with:
          app-id: ${{ secrets.WORKFLOWGATEKEEPER_APP_ID }}
          private-key: ${{ secrets.WORKFLOWGATEKEEPER_PRIVATEKEY }}
          repositories: "goutils,rpc"

      - name: Configure npm for private packages
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
          echo "@razorpay:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: |
          STATUS=0
          assert-nothing-changed() {
            local diff
            "$@" >/dev/null || return 1
            if ! diff="$(git diff -U1 --color --exit-code)"; then
              printf '\e[31mError: running `\e[1m%s\e[22m` results in modifications that you must check into version control:\e[0m\n%s\n\n' "$*" "$diff" >&2
              git checkout -- .
              STATUS=1
            fi
          }

          # Check if package-lock.json is up to date
          assert-nothing-changed npm install --package-lock-only

          # Run linter
          npm run lint || STATUS=$?

          exit $STATUS
